In [2]:
import pandas as pd 
import numpy as np 
from sklearn import linear_model 
from sklearn.metrics import mean_squared_error, r2_score

In [3]:
dfPa = pd.read_csv('price_availability.csv', sep = ";") 
dfLf = pd.read_csv('listings_final.csv', sep = ";")

In [4]:
dfPa.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4748696 entries, 0 to 4748695
Data columns (total 7 columns):
listing_id        int64
day               object
created           object
available         bool
local_currency    object
local_price       int64
min_nights        int64
dtypes: bool(1), int64(3), object(3)
memory usage: 167.6+ MB

In [5]:
dfLf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 19 columns):
Unnamed: 0                  1000 non-null int64
listing_id                  1000 non-null int64
name                        1000 non-null object
type                        1000 non-null object
city                        1000 non-null object
neighborhood                935 non-null object
latitude                    1000 non-null float64
longitude                   1000 non-null float64
person_capacity             1000 non-null int64
beds                        1000 non-null int64
bedrooms                    1000 non-null int64
bathrooms                   1000 non-null float64
is_rebookable               1000 non-null bool
is_new_listing              1000 non-null bool
is_fully_refundable         1000 non-null bool
is_host_highly_rated        1000 non-null bool
is_business_travel_ready    1000 non-null bool
pricing_weekly_factor       1000 non-null float64
pricing_monthly_factor      1000 non-null float64
dtypes: bool(5), float64(5), int64(5), object(4)
memory usage: 98.7+ KB

In [6]:
# on utilisera listing_id pour les jointure,    
# Du côté Pa il est logique d'utiliser [local_price], en prenant en compte [local_currency]
# Du côté Lf on peut prendre: [city], [person_capacity], [bathrooms]

# La correction veur Pa: local_price / Lf:

In [9]:
#dfinal = pd.sqldf("select dfPa.listing_id from dfPa inner join dfLf on dfPa.listing_id = dfLf.listing_id",locals())
dfinal = pd.merge(dfPa,dfLf, on = 'listing_id')
dfinal.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 402616 entries, 0 to 402615
Data columns (total 25 columns):
listing_id                  402616 non-null int64
day                         402616 non-null object
created                     402616 non-null object
available                   402616 non-null bool
local_currency              402616 non-null object
local_price                 402616 non-null int64
min_nights                  402616 non-null int64
Unnamed: 0                  402616 non-null int64
name                        402616 non-null object
type                        402616 non-null object
city                        402616 non-null object
neighborhood                377260 non-null object
latitude                    402616 non-null float64
longitude                   402616 non-null float64
person_capacity             402616 non-null int64
beds                        402616 non-null int64
bedrooms                    402616 non-null int64
bathrooms                   402616 non-null float64
is_rebookable               402616 non-null bool
is_new_listing              402616 non-null bool
is_fully_refundable         402616 non-null bool
is_host_highly_rated        402616 non-null bool
is_business_travel_ready    402616 non-null bool
pricing_weekly_factor       402616 non-null float64
pricing_monthly_factor      402616 non-null float64
dtypes: bool(6), float64(5), int64(7), object(7)
memory usage: 53.0+ MB

In [11]:
dfinal

,listing_id,day,created,available,local_currency,local_price,min_nights,Unnamed: 0,name,type,...,beds,bedrooms,bathrooms,is_rebookable,is_new_listing,is_fully_refundable,is_host_highly_rated,is_business_travel_ready,pricing_weekly_factor,pricing_monthly_factor
0,17757345,2018-10-14,2018-09-27 10:40:07.000+0000,False,EUR,40,1,540,En plein cœur de Belleville,private_room,...,1,1,1.0,False,False,True,False,False,1.0,1.0
1,17757345,2018-10-14,2018-09-27 06:05:54.000+0000,False,EUR,40,1,540,En plein cœur de Belleville,private_room,...,1,1,1.0,False,False,True,False,False,1.0,1.0
2,17757345,2018-10-14,2018-09-26 19:31:41.000+0000,False,EUR,40,1,540,En plein cœur de Belleville,private_room,...,1,1,1.0,False,False,True,False,False,1.0,1.0
3,17757345,2018-10-05,2018-09-27 10:40:07.000+0000,False,EUR,40,1,540,En plein cœur de Belleville,private_room,...,1,1,1.0,False,False,True,False,False,1.0,1.0
4,17757345,2018-10-05,2018-09-27 06:05:54.000+0000,False,EUR,40,1,540,En plein cœur de Belleville,private_room,...,1,1,1.0,False,False,True,False,False,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
402611,23282000,2018-11-11,2018-09-27 06:15:34.000+0000,True,EUR,690,15,744,Professional Fashion #Showroom #Events,entire_home,...,1,2,1.5,False,False,True,True,False,1.0,1.0
402612,23282000,2018-11-11,2018-09-26 19:31:26.000+0000,True,EUR,690,15,744,Professional Fashion #Showroom #Events,entire_home,...,1,2,1.5,False,False,True,True,False,1.0,1.0
402613,23282000,2018-10-23,2018-09-27 10:39:53.000+0000,True,EUR,690,15,744,Professional Fashion #Showroom #Events,entire_home,...,1,2,1.5,False,False,True,True,False,1.0,1.0
402614,23282000,2018-10-23,2018-09-27 06:15:34.000+0000,True,EUR,690,15,744,Professional Fashion #Showroom #Events,entire_home,...,1,2,1.5,False,False,True,True,False,1.0,1.0
402615,23282000,2018-10-23,2018-09-26 19:31:26.000+0000,True,EUR,690,15,744,Professional Fashion #Showroom #Events,entire_home,...,1,2,1.5,False,False,True,True,False,1.0,1.0